module.exports = [
    {
        id: 1,
        chefUserName: 'Felix',
        chefPassword: 'Felix',
        name: 'Felix',
        about: 'about me',
        pic: '/chef/1.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 2,
        chefUserName: 'Thessa',
        chefPassword: 'Thessa',
        name: 'Thessa',
        about: 'about me',
        pic: '/chef/2.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 3,
        chefUserName: 'Nadia',
        chefPassword: 'Nadia',
        name: 'Nadia',
        about: 'about me',
        pic: '/chef/3.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 4,
        chefUserName: 'Bob',
        chefPassword: 'Bob',
        name: 'Bob',
        about: 'about me',
        pic: '/chef/4.jpg',
        pic1: '/chef/gallery/4-1.jpg',
        pic2: '/chef/gallery/4-2.jpg',
        pic3: '/chef/gallery/4-3.jpg',
        pic4: '/chef/gallery/4-4.jpg'
    },
    {
        id: 5,
        chefUserName: 'Jay',
        chefPassword: 'Jay',
        name: 'Jay',
        about: 'about me',
        pic: '/chef/5.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 6,
        chefUserName: 'Ruffles',
        chefPassword: 'Ruffles',
        name: 'Ruffles',
        about: 'about me',
        pic: '/chef/6.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 7,
        chefUserName: 'Kamarjit',
        chefPassword: 'Kamarjit',
        name: 'Kamarjit',
        about: 'about me',
        pic: '/chef/7.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
    {
        id: 8,
        chefUserName: 'Puttin',
        chefPassword: 'Puttin',
        name: 'Puttin',
        about: 'about me',
        pic: '/chef/8.jpg',
        pic1: '',
        pic2: '',
        pic3: '',
        pic4: ''
    },
  ];