module.exports = [
    {
        id: 1,
        name: 'Fish and Chips',
        description: 'Fish and chips is a popular hot dish consisting of fried fish in crispy batter, served with chips. The dish originated in England, where these two components had been introduced from separate immigrant cultures; it is not known who created the culinary fusion that became the emblematic British meal.',
        pic: '/food/1.jpg',
        cuisine: 'British',
        chefId: '6',
    },
    {
        id: 2,
        name: 'Spaghetti',
        description: 'It is a staple food of traditional Italian cuisine. Like other pasta, spaghetti is made of milled wheat and water and sometimes enriched with vitamins and minerals. Italian spaghetti is typically made from durum wheat semolina',
        pic: '/food/2.jpg',
        cuisine: 'Italian',
        chefId: '4',
    },
    {
        id: 3,
        name: 'Lasagna',
        description: 'Lasagne are a type of pasta, possibly one of the oldest types, made of very wide, flat sheets. Either term can also refer to an Italian dish made of stacked layers of lasagne alternating with fillings',
        pic: '/food/3.jpg',
        cuisine: 'Italian',
        chefId: '4',
    },
    {
        id: 4,
        name: 'Burrito',
        description: 'A burrito is a dish in Mexican and Tex-Mex cuisine that took form in California cuisine, consisting of a flour tortilla wrapped into a sealed cylindrical shape around various ingredients.',
        pic: '/food/4.jpg',
        cuisine: 'Mexican',
        chefId: '6',
    },
    {
        id: 5,
        name: 'Italian Sausage and Bell Pepper Polenta Bake',
        description: 'Italian Sausage and Bell Pepper Polenta Bake is a heartier, make-ahead gluten-free twist on pizza with the classic combination of Italian sausage and peppers.  It’s perfect cool-weather comfort food!',
        pic: '/food/5.jpg',
        cuisine: 'Italian',
        chefId: '4',
    },
    {
        id: 6,
        name: 'Italian Beef and Farro Stuffed Peppers',
        description: 'Stout Braised Beef Short Ribs and Colcannon are long on flavor and ease with hearty, delicious Irish-inspired slowly-simmered fall-off-the-bone comfort food goodness!',
        pic: '/food/6.jpg',
        cuisine: 'Italian',
        chefId: '4',
    },
    {
        id: 7,
        name: 'Mediterranean Fish en Papillote',
        description: 'Mediterranean Fish en Papillote has all the classic flavors of that sunny region with tomatoes, olives, capers, garlic, olive oil, wine and lemon–all wrapped up in parchment paper parcels!',
        pic: '/food/7.jpg',
        cuisine: 'Mediterranean',
        chefId: '6',
    },
    {
        id: 8,
        name: 'Pistachio Crusted Fish with Lemon Dill Aioli',
        description: 'Pistachio Crusted Fish with Lemon Dill Aioli is an easy restaurant-quality meal that’s perfect for date night and it’s ready in 30 minutes!',
        pic: '/food/8.jpg',
        cuisine: 'Indian',
        chefId: '6',
    },
    {
        id: 9,
        name: 'Curried Chickpea Encrusted Fish with Jalapeno Lime Tartar Sauce',
        description: 'Curried Chickpea Encrusted Fish with Jalapeno Lime Tartar Sauce is the perfect crunchy nut-free topping!  Roasted chickpeas make a great crispy, crunchy topping everyone can enjoy!',
        pic: '/food/9.jpg',
        cuisine: 'Mexican',
        chefId: '1',
    },
    {
        id: 10,
        name: 'Sheet Pan Thai Sweet Chili – Lime Baked Fish with Garlic Broccolini',
        description: 'Sheet Pan Thai Sweet Chili – Lime Baked Fish with Garlic Broccolini is an easy, healthful flavor-packed meal perfect for a weeknight or date night dinner!',
        pic: '/food/10.jpg',
        cuisine: 'Thai',
        chefId: '1',
    },
    {
        id: 11,
        name: 'Baked Fish with Cherry Tomato Olive Sauce + Lemon Chive Asiago Orzo',
        description: 'Baked Fish with Cherry Tomato-Olive Sauce and Lemon Chive Asiago Orzo makes an easy springtime dinner for two that rocks with flavor!',
        pic: '/food/11.jpg',
        cuisine: 'Mexican',
        chefId: '1',
    },

  ];